// Code generated by vk-gen. DO NOT EDIT.

//go:build windows

package vk

import (
	"fmt"
	"syscall"
	"unsafe"
)

var vulkan *syscall.DLL
var getInstanceProcAddr uintptr

// Init loads the Vulkan library and core functions.
func Init() error {
	var err error
	vulkan, err = syscall.LoadDLL("vulkan-1.dll")
	if err != nil {
		return fmt.Errorf("failed to load vulkan-1.dll: %w", err)
	}

	proc, err := vulkan.FindProc("vkGetInstanceProcAddr")
	if err != nil {
		return fmt.Errorf("vkGetInstanceProcAddr not found: %w", err)
	}
	getInstanceProcAddr = proc.Addr()

	return nil
}

// GetInstanceProcAddr returns the address of a Vulkan function.
func GetInstanceProcAddr(instance Instance, name string) uintptr {
	cname := append([]byte(name), 0)
	r, _, _ := syscall.SyscallN(getInstanceProcAddr,
		uintptr(instance),
		uintptr(unsafe.Pointer(&cname[0])))
	return r
}

// getDeviceProcAddrFn is the cached vkGetDeviceProcAddr function pointer.
var getDeviceProcAddrFn uintptr

// GetDeviceProcAddr returns the address of a device-level Vulkan function.
func GetDeviceProcAddr(device Device, name string) uintptr {
	if getDeviceProcAddrFn == 0 {
		// Load vkGetDeviceProcAddr from instance
		getDeviceProcAddrFn = GetInstanceProcAddr(0, "vkGetDeviceProcAddr")
	}
	if getDeviceProcAddrFn == 0 {
		return 0
	}
	cname := append([]byte(name), 0)
	r, _, _ := syscall.SyscallN(getDeviceProcAddrFn,
		uintptr(device),
		uintptr(unsafe.Pointer(&cname[0])))
	return r
}

// LoadGlobalCommands loads Vulkan commands that don't require an instance.
func (c *Commands) LoadGlobal() {
	c.createInstance = GetInstanceProcAddr(0, "vkCreateInstance")
	c.enumerateInstanceExtensionProperties = GetInstanceProcAddr(0, "vkEnumerateInstanceExtensionProperties")
	c.enumerateInstanceLayerProperties = GetInstanceProcAddr(0, "vkEnumerateInstanceLayerProperties")
	c.enumerateInstanceVersion = GetInstanceProcAddr(0, "vkEnumerateInstanceVersion")
}

// LoadInstance loads Vulkan commands that require an instance.
func (c *Commands) LoadInstance(instance Instance) {
	c.destroyInstance = GetInstanceProcAddr(instance, "vkDestroyInstance")
	c.enumeratePhysicalDevices = GetInstanceProcAddr(instance, "vkEnumeratePhysicalDevices")
	c.getPhysicalDeviceProperties = GetInstanceProcAddr(instance, "vkGetPhysicalDeviceProperties")
	c.getPhysicalDeviceFeatures = GetInstanceProcAddr(instance, "vkGetPhysicalDeviceFeatures")
	c.getPhysicalDeviceQueueFamilyProperties = GetInstanceProcAddr(instance, "vkGetPhysicalDeviceQueueFamilyProperties")
	c.createDevice = GetInstanceProcAddr(instance, "vkCreateDevice")
	// TODO: Add more instance-level commands
}
