# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%
        threshold: 5%

# Ignore paths from coverage calculation
# HAL backend implementations require real GPU hardware and cannot be unit tested
ignore:
  - "hal/vulkan/**/*"
  - "hal/metal/**/*"
  - "hal/dx12/**/*"
  - "hal/gles/**/*"
  - "hal/software/**/*"
  - "hal/noop/**/*"
  - "examples/**/*"
  - "cmd/**/*"

# Go-specific parser settings
parsers:
  go:
    partials_as_hits: false

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
